version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/usr/frontend:cached'
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - '4000:4000'
    volumes:
      - './backend:/usr/backend:cached'
